// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/messaging/messaging.proto

package proto_messaging

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MessagingService service

type MessagingService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	DestroyByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (MessagingService_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (MessagingService_PingPongService, error)
}

type messagingService struct {
	c    client.Client
	name string
}

func NewMessagingService(name string, c client.Client) MessagingService {
	return &messagingService{
		c:    c,
		name: name,
	}
}

func (c *messagingService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MessagingService.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "MessagingService.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingService) DestroyByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MessagingService.DestroyByID", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (MessagingService_StreamService, error) {
	req := c.c.NewRequest(c.name, "MessagingService.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &messagingServiceStream{stream}, nil
}

type MessagingService_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type messagingServiceStream struct {
	stream client.Stream
}

func (x *messagingServiceStream) Close() error {
	return x.stream.Close()
}

func (x *messagingServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *messagingServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagingServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagingServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messagingService) PingPong(ctx context.Context, opts ...client.CallOption) (MessagingService_PingPongService, error) {
	req := c.c.NewRequest(c.name, "MessagingService.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &messagingServicePingPong{stream}, nil
}

type MessagingService_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type messagingServicePingPong struct {
	stream client.Stream
}

func (x *messagingServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *messagingServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *messagingServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagingServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagingServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *messagingServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MessagingService service

type MessagingServiceHandler interface {
	Call(context.Context, *Request, *Response) error
	List(context.Context, *ListRequest, *ListResponse) error
	DestroyByID(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, MessagingService_StreamStream) error
	PingPong(context.Context, MessagingService_PingPongStream) error
}

func RegisterMessagingServiceHandler(s server.Server, hdlr MessagingServiceHandler, opts ...server.HandlerOption) error {
	type messagingService interface {
		Call(ctx context.Context, in *Request, out *Response) error
		List(ctx context.Context, in *ListRequest, out *ListResponse) error
		DestroyByID(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type MessagingService struct {
		messagingService
	}
	h := &messagingServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MessagingService{h}, opts...))
}

type messagingServiceHandler struct {
	MessagingServiceHandler
}

func (h *messagingServiceHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MessagingServiceHandler.Call(ctx, in, out)
}

func (h *messagingServiceHandler) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.MessagingServiceHandler.List(ctx, in, out)
}

func (h *messagingServiceHandler) DestroyByID(ctx context.Context, in *Request, out *Response) error {
	return h.MessagingServiceHandler.DestroyByID(ctx, in, out)
}

func (h *messagingServiceHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MessagingServiceHandler.Stream(ctx, m, &messagingServiceStreamStream{stream})
}

type MessagingService_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type messagingServiceStreamStream struct {
	stream server.Stream
}

func (x *messagingServiceStreamStream) Close() error {
	return x.stream.Close()
}

func (x *messagingServiceStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *messagingServiceStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagingServiceStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagingServiceStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *messagingServiceHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MessagingServiceHandler.PingPong(ctx, &messagingServicePingPongStream{stream})
}

type MessagingService_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type messagingServicePingPongStream struct {
	stream server.Stream
}

func (x *messagingServicePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *messagingServicePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *messagingServicePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagingServicePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagingServicePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *messagingServicePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
