// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/messaging/messaging.proto

package proto_messaging

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest_MessagingListType int32

const (
	ListRequest_Public    ListRequest_MessagingListType = 0
	ListRequest_Private   ListRequest_MessagingListType = 1
	ListRequest_Protected ListRequest_MessagingListType = 2
)

var ListRequest_MessagingListType_name = map[int32]string{
	0: "Public",
	1: "Private",
	2: "Protected",
}

var ListRequest_MessagingListType_value = map[string]int32{
	"Public":    0,
	"Private":   1,
	"Protected": 2,
}

func (x ListRequest_MessagingListType) String() string {
	return proto.EnumName(ListRequest_MessagingListType_name, int32(x))
}

func (ListRequest_MessagingListType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2694837308dc07a6, []int{3, 0}
}

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2694837308dc07a6, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2694837308dc07a6, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Errors               []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2694837308dc07a6, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ListRequest struct {
	MessageType          ListRequest_MessagingListType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=proto.messaging.ListRequest_MessagingListType" json:"message_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2694837308dc07a6, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetMessageType() ListRequest_MessagingListType {
	if m != nil {
		return m.MessageType
	}
	return ListRequest_Public
}

type ListResponse struct {
	Messages             string   `protobuf:"bytes,1,opt,name=messages,proto3" json:"messages,omitempty"`
	Errors               []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2694837308dc07a6, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetMessages() string {
	if m != nil {
		return m.Messages
	}
	return ""
}

func (m *ListResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2694837308dc07a6, []int{5}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2694837308dc07a6, []int{6}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_2694837308dc07a6, []int{7}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_2694837308dc07a6, []int{8}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.messaging.ListRequest_MessagingListType", ListRequest_MessagingListType_name, ListRequest_MessagingListType_value)
	proto.RegisterType((*Message)(nil), "proto.messaging.Message")
	proto.RegisterType((*Request)(nil), "proto.messaging.Request")
	proto.RegisterType((*Response)(nil), "proto.messaging.Response")
	proto.RegisterType((*ListRequest)(nil), "proto.messaging.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "proto.messaging.ListResponse")
	proto.RegisterType((*StreamingRequest)(nil), "proto.messaging.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "proto.messaging.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "proto.messaging.Ping")
	proto.RegisterType((*Pong)(nil), "proto.messaging.Pong")
}

func init() { proto.RegisterFile("proto/messaging/messaging.proto", fileDescriptor_2694837308dc07a6) }

var fileDescriptor_2694837308dc07a6 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xcf, 0x8f, 0x93, 0x40,
	0x18, 0x2d, 0x14, 0x69, 0xfb, 0xb1, 0xae, 0xec, 0x44, 0x0d, 0xe2, 0xaf, 0x75, 0x4e, 0x78, 0x10,
	0x37, 0xab, 0x37, 0xa3, 0x87, 0x15, 0x0f, 0x4d, 0xdc, 0x04, 0xa9, 0x77, 0xc3, 0xe2, 0x17, 0x42,
	0x2c, 0x0c, 0xce, 0x4c, 0x37, 0xe1, 0x8f, 0xf1, 0xaf, 0xf4, 0x1f, 0x30, 0x0c, 0x03, 0x36, 0xa5,
	0xed, 0x61, 0x4f, 0xcc, 0xfb, 0xde, 0xe3, 0xcd, 0xfb, 0xde, 0xc0, 0xcb, 0x9a, 0x33, 0xc9, 0xde,
	0x96, 0x28, 0x44, 0x9a, 0x17, 0x55, 0xfe, 0xff, 0x14, 0x2a, 0x86, 0x3c, 0x50, 0x9f, 0x70, 0x18,
	0xd3, 0xa7, 0x30, 0xbb, 0x56, 0x00, 0x89, 0x0b, 0x53, 0x91, 0x36, 0x9e, 0x71, 0x6e, 0x04, 0x8b,
	0xa4, 0x3d, 0xd2, 0x37, 0x30, 0x4b, 0xf0, 0xf7, 0x06, 0x85, 0x24, 0xa7, 0x60, 0x2e, 0x23, 0xc5,
	0x4d, 0x13, 0x73, 0x19, 0x11, 0x02, 0x56, 0x95, 0x96, 0xe8, 0x99, 0x4a, 0xad, 0xce, 0xf4, 0x3d,
	0xcc, 0x13, 0x14, 0x35, 0xab, 0x84, 0x32, 0x2b, 0x45, 0xde, 0x9b, 0x95, 0x22, 0x27, 0x8f, 0xc1,
	0x46, 0xce, 0x19, 0x17, 0x9e, 0x79, 0x3e, 0x0d, 0x16, 0x89, 0x46, 0xf4, 0x8f, 0x01, 0xce, 0xd7,
	0x42, 0xc8, 0xfe, 0xa6, 0x6f, 0x70, 0xd2, 0xc5, 0xc3, 0x1f, 0xb2, 0xa9, 0x51, 0x59, 0x9c, 0x5e,
	0x86, 0xe1, 0x4e, 0xf2, 0x70, 0xeb, 0x9f, 0xf0, 0xba, 0x9f, 0xb6, 0xc3, 0xef, 0x4d, 0x8d, 0x89,
	0xa3, 0x3d, 0x5a, 0x40, 0x3f, 0xc0, 0xd9, 0x48, 0x41, 0x00, 0xec, 0x78, 0x73, 0xb3, 0x2e, 0x32,
	0x77, 0x42, 0x1c, 0x98, 0xc5, 0xbc, 0xb8, 0x4d, 0x25, 0xba, 0x06, 0xb9, 0x0f, 0x8b, 0x98, 0x33,
	0x89, 0x99, 0xc4, 0x9f, 0xae, 0x49, 0xaf, 0xe0, 0xa4, 0xbb, 0x4a, 0x6f, 0xe6, 0xc3, 0x5c, 0x7b,
	0x0b, 0xbd, 0xde, 0x80, 0x0f, 0xee, 0x18, 0x80, 0xbb, 0x92, 0x1c, 0xd3, 0xb2, 0xa8, 0xf2, 0x7e,
	0xcf, 0x87, 0x70, 0x2f, 0x63, 0x9b, 0x4a, 0xea, 0x52, 0x3b, 0x40, 0x5f, 0xc3, 0xd9, 0x96, 0x52,
	0x5f, 0xb9, 0x5f, 0xfa, 0x02, 0xac, 0xb8, 0xa8, 0x54, 0xb1, 0x42, 0x72, 0xf6, 0x0b, 0x35, 0xad,
	0x91, 0xe2, 0xd9, 0x61, 0xfe, 0xf2, 0xaf, 0x09, 0xee, 0x50, 0xcb, 0x0a, 0xf9, 0x6d, 0x91, 0x21,
	0xf9, 0x08, 0xd6, 0xe7, 0x74, 0xbd, 0x26, 0xde, 0xa8, 0x6f, 0x9d, 0xdb, 0x7f, 0xb2, 0x87, 0xe9,
	0x72, 0xd2, 0x09, 0xf9, 0x02, 0x56, 0x5b, 0x16, 0x79, 0x76, 0xec, 0xb9, 0xfc, 0xe7, 0x07, 0xd8,
	0xc1, 0x26, 0x02, 0x27, 0xc2, 0x36, 0x66, 0x73, 0xd5, 0x2c, 0xa3, 0xbb, 0x86, 0x59, 0x81, 0xdd,
	0x75, 0x49, 0x5e, 0x8d, 0x64, 0xbb, 0xcf, 0xe1, 0xd3, 0x63, 0x92, 0xde, 0xf2, 0xc2, 0x20, 0x9f,
	0x60, 0xde, 0xb6, 0xae, 0x9a, 0x7d, 0x34, 0xfa, 0xa7, 0xa5, 0xfc, 0x3d, 0x63, 0x56, 0xe5, 0x74,
	0x12, 0x18, 0x17, 0xc6, 0x8d, 0xad, 0xb8, 0x77, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x94,
	0xe5, 0xdb, 0xab, 0x03, 0x00, 0x00,
}
