// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/messaging/messaging.proto

package proto_messaging

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Messaging service

type MessagingService interface {
	Call(ctx context.Context, in *MessagingRequest, opts ...client.CallOption) (*MessagingResponse, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Messaging_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Messaging_PingPongService, error)
}

type messagingService struct {
	c    client.Client
	name string
}

func NewMessagingService(name string, c client.Client) MessagingService {
	return &messagingService{
		c:    c,
		name: name,
	}
}

func (c *messagingService) Call(ctx context.Context, in *MessagingRequest, opts ...client.CallOption) (*MessagingResponse, error) {
	req := c.c.NewRequest(c.name, "Messaging.Call", in)
	out := new(MessagingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Messaging_StreamService, error) {
	req := c.c.NewRequest(c.name, "Messaging.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &messagingServiceStream{stream}, nil
}

type Messaging_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type messagingServiceStream struct {
	stream client.Stream
}

func (x *messagingServiceStream) Close() error {
	return x.stream.Close()
}

func (x *messagingServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *messagingServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagingServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagingServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messagingService) PingPong(ctx context.Context, opts ...client.CallOption) (Messaging_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Messaging.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &messagingServicePingPong{stream}, nil
}

type Messaging_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type messagingServicePingPong struct {
	stream client.Stream
}

func (x *messagingServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *messagingServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *messagingServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagingServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagingServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *messagingServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Messaging service

type MessagingHandler interface {
	Call(context.Context, *MessagingRequest, *MessagingResponse) error
	Stream(context.Context, *StreamingRequest, Messaging_StreamStream) error
	PingPong(context.Context, Messaging_PingPongStream) error
}

func RegisterMessagingHandler(s server.Server, hdlr MessagingHandler, opts ...server.HandlerOption) error {
	type messaging interface {
		Call(ctx context.Context, in *MessagingRequest, out *MessagingResponse) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Messaging struct {
		messaging
	}
	h := &messagingHandler{hdlr}
	return s.Handle(s.NewHandler(&Messaging{h}, opts...))
}

type messagingHandler struct {
	MessagingHandler
}

func (h *messagingHandler) Call(ctx context.Context, in *MessagingRequest, out *MessagingResponse) error {
	return h.MessagingHandler.Call(ctx, in, out)
}

func (h *messagingHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MessagingHandler.Stream(ctx, m, &messagingStreamStream{stream})
}

type Messaging_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type messagingStreamStream struct {
	stream server.Stream
}

func (x *messagingStreamStream) Close() error {
	return x.stream.Close()
}

func (x *messagingStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *messagingStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagingStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagingStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *messagingHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MessagingHandler.PingPong(ctx, &messagingPingPongStream{stream})
}

type Messaging_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type messagingPingPongStream struct {
	stream server.Stream
}

func (x *messagingPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *messagingPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *messagingPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *messagingPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *messagingPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *messagingPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
