// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package proto_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MailingList          bool     `protobuf:"varint,4,opt,name=mailing_list,json=mailingList,proto3" json:"mailing_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetMailingList() bool {
	if m != nil {
		return m.MailingList
	}
	return false
}

type Request struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MailingList          bool     `protobuf:"varint,4,opt,name=mailing_list,json=mailingList,proto3" json:"mailing_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Request) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Request) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Request) GetMailingList() bool {
	if m != nil {
		return m.MailingList
	}
	return false
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Errors               []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "proto.user.User")
	proto.RegisterType((*Request)(nil), "proto.user.Request")
	proto.RegisterType((*Response)(nil), "proto.user.Response")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x90, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x4d, 0x72, 0xe4, 0xb2, 0x73, 0x62, 0xb1, 0xfe, 0x61, 0x51, 0x84, 0x98, 0x2a, 0x55,
	0x04, 0xc5, 0xce, 0xce, 0x34, 0x07, 0x62, 0xb1, 0x62, 0x7d, 0xac, 0x32, 0x1e, 0x0b, 0x49, 0xf6,
	0x9c, 0xd9, 0x88, 0x1f, 0x5f, 0x32, 0xe6, 0x10, 0xbf, 0x80, 0xcd, 0x2e, 0xef, 0xf7, 0x8a, 0x1f,
	0xf3, 0xe0, 0x74, 0x47, 0x21, 0x86, 0xeb, 0x91, 0x91, 0xe4, 0x69, 0x24, 0x6b, 0x90, 0xaf, 0x99,
	0x48, 0x35, 0xc2, 0xe2, 0x85, 0x91, 0xf4, 0x11, 0xa4, 0xeb, 0xd6, 0x24, 0x65, 0x52, 0x67, 0x36,
	0x5d, 0xb7, 0xfa, 0x12, 0xe0, 0xdd, 0x13, 0xc7, 0xcd, 0xe0, 0x7a, 0x34, 0x69, 0x99, 0xd4, 0xca,
	0x2a, 0x21, 0x4f, 0xae, 0x47, 0x7d, 0x01, 0xaa, 0x73, 0xfb, 0x36, 0x93, 0xb6, 0x98, 0x80, 0x94,
	0x57, 0x70, 0xd8, 0x3b, 0xdf, 0xf9, 0x61, 0xbb, 0xe9, 0x3c, 0x47, 0xb3, 0x28, 0x93, 0xba, 0xb0,
	0xab, 0x99, 0x3d, 0x7a, 0x8e, 0xd5, 0x17, 0x2c, 0x2d, 0x7e, 0x8c, 0xc8, 0xf1, 0xbf, 0xcd, 0xf7,
	0x50, 0x58, 0xe4, 0x5d, 0x18, 0x18, 0xb5, 0x81, 0x65, 0x8f, 0xcc, 0x6e, 0x8b, 0xe2, 0x57, 0x76,
	0x1f, 0xf5, 0x19, 0xe4, 0x48, 0x14, 0x88, 0x4d, 0x5a, 0x66, 0xb5, 0xb2, 0x73, 0xba, 0x69, 0x61,
	0x35, 0xcd, 0xf5, 0x8c, 0xf4, 0xe9, 0xdf, 0x50, 0xdf, 0x41, 0xfe, 0x40, 0xe8, 0x22, 0xea, 0xe3,
	0xe6, 0x77, 0xd4, 0x66, 0x3e, 0xed, 0xfc, 0xe4, 0x2f, 0xfc, 0xb1, 0x56, 0x07, 0xaf, 0xb9, 0xe0,
	0xdb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x52, 0x13, 0xd5, 0x3d, 0xa0, 0x01, 0x00, 0x00,
}
